# Generated by Django 3.2.13 on 2022-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.TextField(max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
    ]
