version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - nginx
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram_project/.env
    environment:
      - POSTGRES_DB=postgres-foodgram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tgda$m5d
  web:
    build: ../backend/foodgram_project/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/images/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram_project/.env
    environment:
      DB_HOST: db
      POSTGRES_PASSWORD: tgda$m5d

volumes:
  static_value:
  media_value: