# Generated by Django 3.2.13 on 2022-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220510_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('author',), 'verbose_name': 'Список подписок', 'verbose_name_plural': 'Список подписок'},
        ),
    ]
